// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGdvtuh0_btROusM_H5g4bHbxpCxAJ7Os',
    appId: '1:745796263660:web:dd9ed8e83ac4d9b83fcfc9',
    messagingSenderId: '745796263660',
    projectId: 'crealify-chatapp',
    authDomain: 'crealify-chatapp.firebaseapp.com',
    storageBucket: 'crealify-chatapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA58-iw_QnBHITQz9Sr0tm4xYeYFG4wA0g',
    appId: '1:745796263660:android:c66b96ead078006d3fcfc9',
    messagingSenderId: '745796263660',
    projectId: 'crealify-chatapp',
    storageBucket: 'crealify-chatapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9qJMz9rffkGW595AZT-SpmjtdK3tKthg',
    appId: '1:745796263660:ios:8324fdd66c89debe3fcfc9',
    messagingSenderId: '745796263660',
    projectId: 'crealify-chatapp',
    storageBucket: 'crealify-chatapp.firebasestorage.app',
    iosBundleId: 'com.example.chatappFlutter',
  );
}
